from .personnage import Personnage
from .aurore import Aurore
from .akane import Akane
from .laura import Laura
from .bob import Bob
from .william import William
from .erika import Erika
from .agentf import AgentF
from .agentk import AgentK
from .eliza import Eliza